//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spartacus.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public string Credential { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Ip { get; set; }
        public System.DateTime LoginDateTime { get; set; }
    }
}
